#??????

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bugcheck?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root  
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5                                # ??????????????
      initial-size: 5                            # ??????
      max-total: 5                               # ?????
      max-wait-millis: 150                       # ?????????????

