
#??????

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bugcheck?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5                                # ??????????????
      initial-size: 5                            # ??????
      max-total: 5                               # ?????
      max-wait-millis: 150                       # ?????????????
  redis:
    # 改成自己redis的ip地址
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        # 最大阻塞等待时间(负数表示没限制)
        max-active: 20
        max-wait: -1
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1449722625@qq.com  #发送邮件的邮箱地址
    password: yhgnkcqapocgbaec  #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 1449722625@qq.com  # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

# mybatis??
mybatis:
  mapper-locations: classpath:com/example/bugcheck/mapper/*.xml    # mapper??????
  type-aliases-package: com.example.bugcheck.pojo    # ????????
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #???????sql??
    map-underscore-to-camel-case: true

